import time
import json
import logging
from typing import Optional, List, Tuple, Set

from pydantic import BaseModel

from config import config
from core.db import get_pool

logger = logging.getLogger(__name__)


class NetworkDevice(BaseModel):
    ip: str
    mac: str
    vendor: str = "Unknown"
    hostname: str = ""
    is_new: bool = False
    raw_mdns_name: Optional[str] = None
    raw_ssdp_server: Optional[str] = None
    raw_netbios_name: Optional[str] = None
    friendly_name: Optional[str] = None
    device_type: Optional[str] = None
    owner: Optional[str] = None


class BLEDevice(BaseModel):
    address: str
    name: str = "Unknown"
    rssi: int
    manufacturer_data_hex: Optional[str] = None
    service_uuids: Optional[str] = None
    tx_power: Optional[int] = None
    rssi_history: str = "[]"
    proximity: str = "Unknown"
    fingerprint: Optional[str] = None


class HourlyStats(BaseModel):
    avg_network_devices: float
    new_macs: List[str]
    gone_macs: List[str]
    ble_device_count: int
    unwhitelisted_count: int = 0


class DatabaseManager:
    """Postgres (Supabase) access layer. Every classmethod acquires a
    connection from the shared pool (core/db.py) per call; a few (marked
    below) explicitly wrap multiple statements in a transaction to preserve
    the atomicity the old single-SQLite-connection-plus-commit() pattern
    gave for free."""

    @classmethod
    async def get_db(cls):
        """Returns the shared connection pool. Kept as a classmethod (rather
        than having every caller import core.db directly) so existing raw
        `db = await DatabaseManager.get_db(); await db.execute(...)` call
        sites elsewhere in the codebase keep working unchanged — asyncpg.Pool
        exposes the same execute()/fetch()/fetchval() convenience methods a
        single connection does."""
        return get_pool()

    @classmethod
    async def close(cls):
        from core.db import close_pool
        await close_pool()

    @classmethod
    async def init_db(cls):
        """Create tables if they don't exist. No ALTER-TABLE schema
        versioning needed here (unlike the old SQLite-era _init_tables) —
        this is a fresh Postgres schema with every column declared upfront."""
        pool = get_pool()
        async with pool.acquire() as db:
            await db.execute("""
                CREATE TABLE IF NOT EXISTS network_devices (
                    mac TEXT PRIMARY KEY,
                    ip TEXT,
                    vendor TEXT,
                    hostname TEXT,
                    first_seen DOUBLE PRECISION NOT NULL,
                    last_seen DOUBLE PRECISION NOT NULL,
                    is_active INTEGER DEFAULT 1,
                    raw_mdns_name TEXT,
                    raw_ssdp_server TEXT,
                    raw_netbios_name TEXT,
                    is_known INTEGER DEFAULT 0,
                    banner_grab_attempted_at DOUBLE PRECISION,
                    banner_grab_attempts INTEGER DEFAULT 0,
                    friendly_name TEXT,
                    device_type TEXT,
                    owner TEXT
                )
            """)
            await db.execute("""
                CREATE TABLE IF NOT EXISTS scan_history (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    scan_time DOUBLE PRECISION NOT NULL,
                    device_count INTEGER NOT NULL
                )
            """)
            await db.execute("""
                CREATE TABLE IF NOT EXISTS dns_queries (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    timestamp DOUBLE PRECISION NOT NULL,
                    src_ip TEXT NOT NULL,
                    query_name TEXT NOT NULL,
                    query_type TEXT
                )
            """)
            await db.execute("CREATE INDEX IF NOT EXISTS idx_dns_queries_src_ts ON dns_queries(src_ip, timestamp)")
            await db.execute("""
                CREATE TABLE IF NOT EXISTS bt_devices (
                    address TEXT PRIMARY KEY,
                    name TEXT,
                    rssi INTEGER,
                    last_seen DOUBLE PRECISION NOT NULL,
                    manufacturer_data_hex TEXT,
                    service_uuids TEXT,
                    is_known INTEGER DEFAULT 0,
                    tx_power INTEGER,
                    rssi_history TEXT DEFAULT '[]',
                    fingerprint TEXT
                )
            """)
            await db.execute("CREATE INDEX IF NOT EXISTS idx_bt_devices_fingerprint ON bt_devices(fingerprint)")
            await db.execute("""
                CREATE TABLE IF NOT EXISTS oui_mappings (
                    mac_prefix TEXT PRIMARY KEY,
                    vendor TEXT NOT NULL
                )
            """)
            await db.execute("""
                CREATE TABLE IF NOT EXISTS monitored_hosts (
                    ip TEXT PRIMARY KEY,
                    is_active INTEGER DEFAULT 1
                )
            """)
            await db.execute("""
                CREATE TABLE IF NOT EXISTS device_ports (
                    mac TEXT,
                    port INTEGER,
                    service TEXT,
                    first_seen DOUBLE PRECISION NOT NULL,
                    last_seen DOUBLE PRECISION NOT NULL,
                    is_active INTEGER DEFAULT 1,
                    PRIMARY KEY (mac, port)
                )
            """)
            await db.execute("""
                CREATE TABLE IF NOT EXISTS port_history (
                    mac TEXT,
                    port INTEGER,
                    service TEXT,
                    event TEXT,
                    timestamp DOUBLE PRECISION
                )
            """)
            await db.execute("CREATE INDEX IF NOT EXISTS idx_port_history_mac ON port_history(mac)")
            await db.execute("""
                CREATE TABLE IF NOT EXISTS events (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    timestamp DOUBLE PRECISION NOT NULL,
                    category TEXT NOT NULL,
                    severity TEXT NOT NULL,
                    message TEXT NOT NULL,
                    related_id TEXT
                )
            """)
            await db.execute("""
                CREATE TABLE IF NOT EXISTS jobs (
                    id TEXT PRIMARY KEY,
                    job_type TEXT,
                    target TEXT,
                    status TEXT,
                    requester_chat_id BIGINT,
                    created_at DOUBLE PRECISION,
                    started_at DOUBLE PRECISION,
                    finished_at DOUBLE PRECISION,
                    result_summary TEXT,
                    result_path TEXT,
                    error TEXT
                )
            """)
            await db.execute("""
                CREATE TABLE IF NOT EXISTS ble_alert_cooldown (
                    vendor_key TEXT PRIMARY KEY,
                    last_alert_at DOUBLE PRECISION NOT NULL
                )
            """)
            await db.execute("""
                CREATE TABLE IF NOT EXISTS honeypot_alert_cooldown (
                    src_ip TEXT PRIMARY KEY,
                    last_alert_at DOUBLE PRECISION NOT NULL
                )
            """)
            await db.execute("""
                CREATE TABLE IF NOT EXISTS resource_alert_cooldown (
                    metric_key TEXT PRIMARY KEY,
                    last_alert_at DOUBLE PRECISION NOT NULL
                )
            """)
            await db.execute("""
                CREATE TABLE IF NOT EXISTS latency_samples (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    timestamp DOUBLE PRECISION NOT NULL,
                    target TEXT NOT NULL,
                    loss_pct DOUBLE PRECISION,
                    jitter_ms DOUBLE PRECISION
                )
            """)
            await db.execute("""
                CREATE TABLE IF NOT EXISTS deferred_scans (
                    mac TEXT PRIMARY KEY,
                    ip TEXT NOT NULL,
                    queued_at DOUBLE PRECISION NOT NULL
                )
            """)
            await db.execute("""
                CREATE TABLE IF NOT EXISTS job_heartbeats (
                    job_name TEXT PRIMARY KEY,
                    last_run_at DOUBLE PRECISION
                )
            """)
            await db.execute("""
                CREATE TABLE IF NOT EXISTS device_maintenance (
                    mac TEXT PRIMARY KEY,
                    until_timestamp DOUBLE PRECISION NOT NULL,
                    reason TEXT
                )
            """)
        logger.info("Database tables initialized.")

    @classmethod
    async def upsert_network_devices(cls, devices: List[NetworkDevice]) -> Tuple[Set[str], Set[str]]:
        """
        Upsert a batch of devices.
        Returns a tuple: (set of newly discovered MACs, set of MACs that went offline).
        """
        pool = get_pool()
        current_time = time.time()
        current_macs = {d.mac for d in devices}
        current_macs_list = list(current_macs)

        async with pool.acquire() as db:
            async with db.transaction():
                # Determine newly discovered MACs
                known_rows = await db.fetch("SELECT mac FROM network_devices")
                known_macs = {row["mac"] for row in known_rows}
                new_macs = current_macs - known_macs

                # Upsert devices
                await db.executemany("""
                    INSERT INTO network_devices (mac, ip, vendor, hostname, first_seen, last_seen, is_active, raw_mdns_name, raw_ssdp_server, raw_netbios_name)
                    VALUES ($1, $2, $3, $4, $5, $6, 1, $7, $8, $9)
                    ON CONFLICT(mac) DO UPDATE SET
                        ip = excluded.ip,
                        vendor = excluded.vendor,
                        hostname = CASE WHEN excluded.hostname != '' THEN excluded.hostname ELSE network_devices.hostname END,
                        last_seen = excluded.last_seen,
                        is_active = 1,
                        raw_mdns_name = CASE WHEN excluded.raw_mdns_name IS NOT NULL THEN excluded.raw_mdns_name ELSE network_devices.raw_mdns_name END,
                        raw_ssdp_server = CASE WHEN excluded.raw_ssdp_server IS NOT NULL THEN excluded.raw_ssdp_server ELSE network_devices.raw_ssdp_server END,
                        raw_netbios_name = CASE WHEN excluded.raw_netbios_name IS NOT NULL THEN excluded.raw_netbios_name ELSE network_devices.raw_netbios_name END
                """, [(d.mac, d.ip, d.vendor, d.hostname, current_time, current_time, d.raw_mdns_name, d.raw_ssdp_server, d.raw_netbios_name) for d in devices])

                # Mark missing devices as inactive, but only after a grace period of missed
                # scans — battery/power-save devices (phones, watches, IoT plugs) routinely
                # skip a single ARP reply without actually leaving the network.
                grace_cutoff = current_time - (config.device_offline_grace_minutes * 60)
                if current_macs_list:
                    gone_rows = await db.fetch(
                        "SELECT mac FROM network_devices WHERE is_active = 1 AND mac != ALL($1::text[]) AND last_seen < $2",
                        current_macs_list, grace_cutoff,
                    )
                    gone_macs = {row["mac"] for row in gone_rows}
                    await db.execute(
                        "UPDATE network_devices SET is_active = 0 WHERE mac != ALL($1::text[]) AND last_seen < $2",
                        current_macs_list, grace_cutoff,
                    )
                else:
                    # Everything is gone (empty scan) — still respect the grace period.
                    gone_rows = await db.fetch("SELECT mac FROM network_devices WHERE is_active = 1 AND last_seen < $1", grace_cutoff)
                    gone_macs = {row["mac"] for row in gone_rows}
                    await db.execute("UPDATE network_devices SET is_active = 0 WHERE last_seen < $1", grace_cutoff)

                # Record scan history
                await db.execute(
                    "INSERT INTO scan_history (scan_time, device_count) VALUES ($1, $2)",
                    current_time, len(devices),
                )

        for d in devices:
            if d.mac in new_macs:
                d.is_new = True

        return new_macs, gone_macs

    @classmethod
    async def get_active_devices(cls) -> List[NetworkDevice]:
        """Get all currently active devices."""
        pool = get_pool()
        rows = await pool.fetch("""
            SELECT mac, ip, vendor, hostname, friendly_name, device_type, owner
            FROM network_devices
            WHERE is_active = 1
            ORDER BY ip
        """)
        return [NetworkDevice(
            mac=r["mac"], ip=r["ip"], vendor=r["vendor"], hostname=r["hostname"],
            friendly_name=r["friendly_name"], device_type=r["device_type"], owner=r["owner"]
        ) for r in rows]

    @classmethod
    async def set_device_name(cls, mac: str, name: str) -> bool:
        pool = get_pool()
        result = await pool.execute("UPDATE network_devices SET friendly_name = $1 WHERE mac = $2", name, mac)
        return result.split()[-1] != "0"

    @classmethod
    async def upsert_bt_devices(cls, devices: List[BLEDevice]) -> Set[str]:
        pool = get_pool()
        current_time = time.time()
        current_macs = {d.address for d in devices}
        current_macs_list = list(current_macs)

        async with pool.acquire() as db:
            known_rows = await db.fetch("SELECT address FROM bt_devices")
            known_macs = {row["address"] for row in known_rows}
            new_macs = current_macs - known_macs

            existing_histories = {}
            if current_macs_list:
                rows = await db.fetch(
                    "SELECT address, rssi_history FROM bt_devices WHERE address = ANY($1::text[])", current_macs_list
                )
                for row in rows:
                    try:
                        existing_histories[row["address"]] = json.loads(row["rssi_history"] or "[]")
                    except json.JSONDecodeError:
                        existing_histories[row["address"]] = []

            upsert_data = []
            for d in devices:
                hist = existing_histories.get(d.address, [])
                hist.append(d.rssi)
                hist = hist[-5:]  # Keep last 5 samples
                d.rssi_history = json.dumps(hist)
                upsert_data.append((d.address, d.name, d.rssi, current_time, d.manufacturer_data_hex, d.service_uuids, d.tx_power, d.rssi_history, d.fingerprint))

            await db.executemany("""
                INSERT INTO bt_devices (address, name, rssi, last_seen, manufacturer_data_hex, service_uuids, tx_power, rssi_history, fingerprint)
                VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
                ON CONFLICT(address) DO UPDATE SET
                    name = CASE WHEN excluded.name != 'Unknown' AND excluded.name != '' THEN excluded.name ELSE bt_devices.name END,
                    rssi = excluded.rssi,
                    last_seen = excluded.last_seen,
                    manufacturer_data_hex = CASE WHEN excluded.manufacturer_data_hex IS NOT NULL THEN excluded.manufacturer_data_hex ELSE bt_devices.manufacturer_data_hex END,
                    service_uuids = CASE WHEN excluded.service_uuids IS NOT NULL THEN excluded.service_uuids ELSE bt_devices.service_uuids END,
                    tx_power = excluded.tx_power,
                    rssi_history = excluded.rssi_history,
                    fingerprint = CASE WHEN excluded.fingerprint IS NOT NULL THEN excluded.fingerprint ELSE bt_devices.fingerprint END
            """, upsert_data)

        return new_macs

    @classmethod
    async def mark_known(cls, mac: str) -> bool:
        pool = get_pool()
        async with pool.acquire() as db:
            async with db.transaction():
                r1 = await db.execute("UPDATE network_devices SET is_known = 1 WHERE mac = $1", mac)
                r2 = await db.execute("UPDATE bt_devices SET is_known = 1 WHERE address = $1", mac)
        return r1.split()[-1] != "0" or r2.split()[-1] != "0"

    @classmethod
    async def is_known(cls, mac: str) -> bool:
        pool = get_pool()
        val1 = await pool.fetchval("SELECT is_known FROM network_devices WHERE mac = $1", mac)
        if val1 == 1:
            return True
        val2 = await pool.fetchval("SELECT is_known FROM bt_devices WHERE address = $1", mac)
        if val2 == 1:
            return True
        return False

    @classmethod
    async def was_fingerprint_seen_recently(cls, fingerprint: str, hours: float = 24.0) -> bool:
        if not fingerprint:
            return False
        pool = get_pool()
        cutoff = time.time() - (hours * 3600)
        val = await pool.fetchval("SELECT 1 FROM bt_devices WHERE fingerprint = $1 AND last_seen >= $2 LIMIT 1", fingerprint, cutoff)
        return val is not None

    @classmethod
    async def get_hourly_stats(cls, hours: int = 1) -> HourlyStats:
        """Compute network statistics over the last `hours` window."""
        pool = get_pool()
        cutoff_time = time.time() - (hours * 3600)

        avg_count = await pool.fetchval(
            "SELECT AVG(device_count) FROM scan_history WHERE scan_time >= $1", cutoff_time
        )
        avg_count = avg_count if avg_count is not None else 0.0

        new_rows = await pool.fetch("SELECT mac FROM network_devices WHERE first_seen >= $1", cutoff_time)
        new_macs = [r["mac"] for r in new_rows]

        gone_rows = await pool.fetch("SELECT mac FROM network_devices WHERE is_active = 0 AND last_seen >= $1", cutoff_time)
        gone_macs = [r["mac"] for r in gone_rows]

        bt_count = await pool.fetchval("SELECT COUNT(address) FROM bt_devices WHERE last_seen >= $1", cutoff_time)

        unwhitelisted_count = await pool.fetchval("SELECT COUNT(*) FROM network_devices WHERE is_active = 1 AND is_known = 0")

        return HourlyStats(
            avg_network_devices=round(avg_count, 1),
            new_macs=new_macs,
            gone_macs=gone_macs,
            ble_device_count=bt_count,
            unwhitelisted_count=unwhitelisted_count
        )

    # OUI Cache Methods
    @classmethod
    async def oui_count(cls) -> int:
        pool = get_pool()
        return await pool.fetchval("SELECT COUNT(*) FROM oui_mappings")

    @classmethod
    async def add_monitored_host(cls, ip: str) -> bool:
        pool = get_pool()
        await pool.execute(
            "INSERT INTO monitored_hosts (ip, is_active) VALUES ($1, 1) ON CONFLICT (ip) DO UPDATE SET is_active = excluded.is_active",
            ip,
        )
        return True

    @classmethod
    async def remove_monitored_host(cls, ip: str) -> bool:
        pool = get_pool()
        result = await pool.execute("UPDATE monitored_hosts SET is_active = 0 WHERE ip = $1", ip)
        return result.split()[-1] != "0"

    @classmethod
    async def get_monitored_hosts(cls) -> List[str]:
        pool = get_pool()
        rows = await pool.fetch("SELECT ip FROM monitored_hosts WHERE is_active = 1")
        return [r["ip"] for r in rows]

    @classmethod
    async def bulk_insert_oui(cls, mappings: List[Tuple[str, str]]):
        pool = get_pool()
        await pool.executemany(
            "INSERT INTO oui_mappings (mac_prefix, vendor) VALUES ($1, $2) ON CONFLICT (mac_prefix) DO UPDATE SET vendor = excluded.vendor",
            mappings,
        )

    @classmethod
    async def lookup_oui(cls, mac_prefix: str) -> Optional[str]:
        pool = get_pool()
        return await pool.fetchval("SELECT vendor FROM oui_mappings WHERE mac_prefix = $1", mac_prefix)

    @classmethod
    async def get_device_ports(cls, mac: str) -> List[dict]:
        pool = get_pool()
        rows = await pool.fetch("SELECT port, service, is_active FROM device_ports WHERE mac = $1", mac)
        return [dict(row) for row in rows]

    @classmethod
    async def upsert_device_ports(cls, mac: str, ports: List[dict]) -> List[dict]:
        """
        ports: list of dicts with 'port' and 'service'
        Returns a list of NEW ports that appeared.
        """
        pool = get_pool()
        current_time = time.time()

        async with pool.acquire() as db:
            async with db.transaction():
                existing_rows = await db.fetch("SELECT port, service, is_active FROM device_ports WHERE mac = $1", mac)
                existing_ports = {row["port"]: row for row in existing_rows}

                new_ports = []
                upsert_data = []
                history_inserts = []

                for p in ports:
                    port = p["port"]
                    service = p["service"]
                    upsert_data.append((mac, port, service, current_time, current_time))
                    if port not in existing_ports or existing_ports[port]["is_active"] == 0:
                        new_ports.append(p)
                        history_inserts.append((mac, port, service, "opened", current_time))

                if upsert_data:
                    await db.executemany("""
                        INSERT INTO device_ports (mac, port, service, first_seen, last_seen, is_active)
                        VALUES ($1, $2, $3, $4, $5, 1)
                        ON CONFLICT(mac, port) DO UPDATE SET
                            service = excluded.service,
                            last_seen = excluded.last_seen,
                            is_active = 1
                    """, upsert_data)

                current_port_nums = {p["port"] for p in ports}
                gone_ports = [p for p in existing_ports if existing_ports[p]["is_active"] == 1 and p not in current_port_nums]
                if gone_ports:
                    await db.execute(
                        "UPDATE device_ports SET is_active = 0 WHERE mac = $1 AND port = ANY($2::integer[])", mac, gone_ports
                    )
                    for gp in gone_ports:
                        history_inserts.append((mac, gp, existing_ports[gp]["service"], "closed", current_time))

                if history_inserts:
                    await db.executemany(
                        "INSERT INTO port_history (mac, port, service, event, timestamp) VALUES ($1, $2, $3, $4, $5)",
                        history_inserts,
                    )

        return new_ports

    @classmethod
    async def log_event(cls, category: str, severity: str, message: str, related_id: Optional[str] = None):
        """Log an event/alert to the database for the dashboard."""
        pool = get_pool()
        await pool.execute(
            "INSERT INTO events (timestamp, category, severity, message, related_id) VALUES ($1, $2, $3, $4, $5)",
            time.time(), category, severity, message, related_id,
        )

    @classmethod
    async def get_devices_needing_banner_grab(cls) -> List[NetworkDevice]:
        pool = get_pool()
        current_time = time.time()

        rows = await pool.fetch("""
            SELECT mac, ip, vendor, hostname, banner_grab_attempted_at, banner_grab_attempts
            FROM network_devices
            WHERE is_active = 1
            AND vendor = 'Unknown'
            AND hostname = ''
        """)

        devices = []
        for r in rows:
            attempts = r["banner_grab_attempts"] or 0
            last_attempt = r["banner_grab_attempted_at"]

            if last_attempt is None:
                devices.append(NetworkDevice(mac=r["mac"], ip=r["ip"], vendor=r["vendor"], hostname=r["hostname"]))
                continue

            cooldown_hours = min(168, 2 ** attempts)
            if current_time - last_attempt >= cooldown_hours * 3600:
                devices.append(NetworkDevice(mac=r["mac"], ip=r["ip"], vendor=r["vendor"], hostname=r["hostname"]))

        return devices

    @classmethod
    async def record_banner_grab_attempt(cls, mac: str, resolved: bool, hostname: str = ""):
        pool = get_pool()
        current_time = time.time()

        if resolved and hostname:
            await pool.execute("""
                UPDATE network_devices
                SET banner_grab_attempted_at = $1,
                    banner_grab_attempts = banner_grab_attempts + 1,
                    hostname = $2
                WHERE mac = $3
            """, current_time, hostname, mac)
        else:
            await pool.execute("""
                UPDATE network_devices
                SET banner_grab_attempted_at = $1,
                    banner_grab_attempts = banner_grab_attempts + 1
                WHERE mac = $2
            """, current_time, mac)

    @classmethod
    async def should_alert_ble_vendor(cls, vendor_key: str, cooldown_hours: float) -> bool:
        pool = get_pool()
        current_time = time.time()

        last_alert_at = await pool.fetchval("SELECT last_alert_at FROM ble_alert_cooldown WHERE vendor_key = $1", vendor_key)

        if last_alert_at is None or (current_time - last_alert_at) >= (cooldown_hours * 3600):
            await pool.execute(
                "INSERT INTO ble_alert_cooldown (vendor_key, last_alert_at) VALUES ($1, $2) ON CONFLICT(vendor_key) DO UPDATE SET last_alert_at = excluded.last_alert_at",
                vendor_key, current_time,
            )
            return True

        return False

    @classmethod
    async def should_alert_honeypot(cls, src_ip: str, cooldown_seconds: float) -> bool:
        pool = get_pool()
        current_time = time.time()

        last_alert_at = await pool.fetchval("SELECT last_alert_at FROM honeypot_alert_cooldown WHERE src_ip = $1", src_ip)

        if last_alert_at is None or (current_time - last_alert_at) >= cooldown_seconds:
            await pool.execute(
                "INSERT INTO honeypot_alert_cooldown (src_ip, last_alert_at) VALUES ($1, $2) ON CONFLICT(src_ip) DO UPDATE SET last_alert_at = excluded.last_alert_at",
                src_ip, current_time,
            )
            return True

        return False

    @classmethod
    async def should_alert_resource(cls, metric_key: str, cooldown_hours: float) -> bool:
        pool = get_pool()
        current_time = time.time()

        last_alert_at = await pool.fetchval("SELECT last_alert_at FROM resource_alert_cooldown WHERE metric_key = $1", metric_key)

        if last_alert_at is None or (current_time - last_alert_at) >= (cooldown_hours * 3600):
            await pool.execute(
                "INSERT INTO resource_alert_cooldown (metric_key, last_alert_at) VALUES ($1, $2) ON CONFLICT(metric_key) DO UPDATE SET last_alert_at = excluded.last_alert_at",
                metric_key, current_time,
            )
            return True

        return False

    @classmethod
    async def queue_deferred_scan(cls, mac: str, ip: str):
        pool = get_pool()
        await pool.execute(
            "INSERT INTO deferred_scans (mac, ip, queued_at) VALUES ($1, $2, $3) ON CONFLICT (mac) DO UPDATE SET ip = excluded.ip, queued_at = excluded.queued_at",
            mac, ip, time.time(),
        )

    @classmethod
    async def get_due_deferred_scans(cls) -> List[Tuple[str, str]]:
        pool = get_pool()
        rows = await pool.fetch("SELECT mac, ip FROM deferred_scans")
        return [(r["mac"], r["ip"]) for r in rows]

    @classmethod
    async def remove_deferred_scan(cls, mac: str):
        pool = get_pool()
        await pool.execute("DELETE FROM deferred_scans WHERE mac = $1", mac)

    @classmethod
    async def log_latency_sample(cls, target: str, loss_pct: float, jitter_ms: float):
        pool = get_pool()
        await pool.execute(
            "INSERT INTO latency_samples (timestamp, target, loss_pct, jitter_ms) VALUES ($1, $2, $3, $4)",
            time.time(), target, loss_pct, jitter_ms,
        )

    @classmethod
    async def cache_oui_entry(cls, prefix: str, vendor: str):
        await cls.bulk_insert_oui([(prefix, vendor)])

    @classmethod
    async def update_device_vendor(cls, mac: str, vendor: str):
        pool = get_pool()
        await pool.execute("UPDATE network_devices SET vendor = $1 WHERE mac = $2", vendor, mac)

    @classmethod
    async def record_scan_heartbeat(cls, job_name: str):
        pool = get_pool()
        await pool.execute(
            "INSERT INTO job_heartbeats (job_name, last_run_at) VALUES ($1, $2) ON CONFLICT(job_name) DO UPDATE SET last_run_at=excluded.last_run_at",
            job_name, time.time(),
        )

    @classmethod
    async def insert_dns_queries(cls, queries: List[Tuple[float, str, str, str]]):
        """Batch insert DNS queries (timestamp, src_ip, query_name, query_type)."""
        pool = get_pool()
        await pool.executemany(
            "INSERT INTO dns_queries (timestamp, src_ip, query_name, query_type) VALUES ($1, $2, $3, $4)",
            queries,
        )

    @classmethod
    async def get_recent_dns_queries(cls, ip: str, limit: int = 50) -> List[dict]:
        pool = get_pool()
        rows = await pool.fetch("""
            SELECT query_name, MAX(timestamp) as last_seen, query_type
            FROM dns_queries
            WHERE src_ip = $1
            GROUP BY query_name, query_type
            ORDER BY last_seen DESC
            LIMIT $2
        """, ip, limit)
        return [dict(row) for row in rows]

    @classmethod
    async def set_maintenance(cls, mac: str, hours: float, reason: str = ""):
        pool = get_pool()
        if hours <= 0:
            await pool.execute("DELETE FROM device_maintenance WHERE mac = $1", mac)
        else:
            until = time.time() + (hours * 3600)
            await pool.execute(
                "INSERT INTO device_maintenance (mac, until_timestamp, reason) VALUES ($1, $2, $3) ON CONFLICT(mac) DO UPDATE SET until_timestamp = excluded.until_timestamp, reason = excluded.reason",
                mac, until, reason,
            )

    @classmethod
    async def is_in_maintenance(cls, mac: str) -> bool:
        pool = get_pool()
        until_timestamp = await pool.fetchval("SELECT until_timestamp FROM device_maintenance WHERE mac = $1", mac)
        if until_timestamp and until_timestamp > time.time():
            return True
        return False
