"""One-off schema setup for the Supabase (Postgres) migration.

Run via: docker compose run --rm bot python -m scripts.init_supabase_schema
Safe to rerun — every statement is CREATE TABLE IF NOT EXISTS.
"""

import asyncio
import logging

import asyncpg

from config import config

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

CONNECT_RETRIES = 3
CONNECT_RETRY_DELAY_SECONDS = 3


async def connect_with_retry(dsn):
    last_exc = None
    for attempt in range(1, CONNECT_RETRIES + 1):
        try:
            return await asyncpg.connect(dsn=dsn)
        except OSError as exc:
            last_exc = exc
            logger.warning(f"Connect attempt {attempt}/{CONNECT_RETRIES} failed ({exc}); retrying...")
            await asyncio.sleep(CONNECT_RETRY_DELAY_SECONDS)
    raise last_exc


SCHEMA_STATEMENTS = [
    """
    CREATE TABLE IF NOT EXISTS network_devices (
        mac TEXT PRIMARY KEY,
        ip TEXT,
        vendor TEXT,
        hostname TEXT,
        first_seen DOUBLE PRECISION NOT NULL,
        last_seen DOUBLE PRECISION NOT NULL,
        is_active INTEGER DEFAULT 1,
        raw_mdns_name TEXT,
        raw_ssdp_server TEXT,
        raw_netbios_name TEXT,
        is_known INTEGER DEFAULT 0,
        banner_grab_attempted_at DOUBLE PRECISION,
        banner_grab_attempts INTEGER DEFAULT 0,
        friendly_name TEXT,
        device_type TEXT,
        owner TEXT
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS scan_history (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        scan_time DOUBLE PRECISION NOT NULL,
        device_count INTEGER NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS dns_queries (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        timestamp DOUBLE PRECISION NOT NULL,
        src_ip TEXT NOT NULL,
        query_name TEXT NOT NULL,
        query_type TEXT
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_dns_queries_src_ts ON dns_queries(src_ip, timestamp)",
    """
    CREATE TABLE IF NOT EXISTS bt_devices (
        address TEXT PRIMARY KEY,
        name TEXT,
        rssi INTEGER,
        last_seen DOUBLE PRECISION NOT NULL,
        manufacturer_data_hex TEXT,
        service_uuids TEXT,
        is_known INTEGER DEFAULT 0,
        tx_power INTEGER,
        rssi_history TEXT DEFAULT '[]',
        fingerprint TEXT
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_bt_devices_fingerprint ON bt_devices(fingerprint)",
    """
    CREATE TABLE IF NOT EXISTS oui_mappings (
        mac_prefix TEXT PRIMARY KEY,
        vendor TEXT NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS monitored_hosts (
        ip TEXT PRIMARY KEY,
        is_active INTEGER DEFAULT 1
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS device_ports (
        mac TEXT,
        port INTEGER,
        service TEXT,
        first_seen DOUBLE PRECISION NOT NULL,
        last_seen DOUBLE PRECISION NOT NULL,
        is_active INTEGER DEFAULT 1,
        PRIMARY KEY (mac, port)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS port_history (
        mac TEXT,
        port INTEGER,
        service TEXT,
        event TEXT,
        timestamp DOUBLE PRECISION
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_port_history_mac ON port_history(mac)",
    """
    CREATE TABLE IF NOT EXISTS events (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        timestamp DOUBLE PRECISION NOT NULL,
        category TEXT NOT NULL,
        severity TEXT NOT NULL,
        message TEXT NOT NULL,
        related_id TEXT
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS jobs (
        id TEXT PRIMARY KEY,
        job_type TEXT,
        target TEXT,
        status TEXT,
        requester_chat_id BIGINT,
        created_at DOUBLE PRECISION,
        started_at DOUBLE PRECISION,
        finished_at DOUBLE PRECISION,
        result_summary TEXT,
        result_path TEXT,
        error TEXT
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS ble_alert_cooldown (
        vendor_key TEXT PRIMARY KEY,
        last_alert_at DOUBLE PRECISION NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS honeypot_alert_cooldown (
        src_ip TEXT PRIMARY KEY,
        last_alert_at DOUBLE PRECISION NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS resource_alert_cooldown (
        metric_key TEXT PRIMARY KEY,
        last_alert_at DOUBLE PRECISION NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS latency_samples (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        timestamp DOUBLE PRECISION NOT NULL,
        target TEXT NOT NULL,
        loss_pct DOUBLE PRECISION,
        jitter_ms DOUBLE PRECISION
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS deferred_scans (
        mac TEXT PRIMARY KEY,
        ip TEXT NOT NULL,
        queued_at DOUBLE PRECISION NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS job_heartbeats (
        job_name TEXT PRIMARY KEY,
        last_run_at DOUBLE PRECISION
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS device_maintenance (
        mac TEXT PRIMARY KEY,
        until_timestamp DOUBLE PRECISION NOT NULL,
        reason TEXT
    )
    """,
]


async def main():
    dsn = config.database_url.get_secret_value()
    if not dsn:
        raise SystemExit("DATABASE_URL is not set in .env")

    logger.info("Connecting to Supabase...")
    conn = await connect_with_retry(dsn)
    try:
        for statement in SCHEMA_STATEMENTS:
            await conn.execute(statement)
        table_count = await conn.fetchval(
            "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = 'public'"
        )
        logger.info(f"Schema applied. {table_count} table(s) present in public schema.")
    finally:
        await conn.close()


if __name__ == "__main__":
    asyncio.run(main())
